name: spartial
description: Spartial lets you automatically skip parts of spotify songs that you don't want to hear.
publish_to: 'none' 

version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_foreground_task: ^3.5.0
  hive:
  hive_flutter:
  receive_sharing_intent: ^1.4.5 
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.2
  minimize_app: ^0.1.1
  custom_refresh_indicator: ^1.0.0
  introduction_screen: ^2.1.0
  url_launcher: ^6.0.17
  uni_links: ^0.5.1
  share_plus: ^3.0.4
  device_info: ^2.0.3
  flutter_screenutil: ^5.0.1+3
  flutter_local_notifications: ^9.2.0
  package_info_plus: ^1.3.0
  spotify:
    git:
      url: https://github.com/rinukkusu/spotify-dart

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon2.png"
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon2.png
    - assets/selection_example_1.png
    - assets/selection_example_2.png
    - assets/selection_example_3.png
    - assets/spartial_notification.png
    - assets/ios_notification.jpg
    - assets/hide_notifications/1.jpg
    - assets/hide_notifications/2.jpg
    - assets/hide_notifications/3.jpg
    - assets/hide_notifications/4.jpg
    - assets/hide_notifications_ios/1.jpg
    - assets/hide_notifications_ios/2.jpg
    - assets/hide_notifications_ios/3.jpg
    - assets/hide_notifications_ios/4.jpg
    - assets/hide_notifications/6.jpg
    - assets/share_instruction.jpg
    - assets/spotify/Spotify_Icon_RGB_Black.png
    - assets/spotify/Spotify_Icon_RGB_White.png
    - assets/spotify/Spotify_Logo_RGB_White.png


